### ISSUE TITLE
Expected and actual are the wrong way around

### ISSUE THREAD

**Issue by holmesjr** [neopragma/bash-spec#1]
```
function to_be {
    _actual_="$1"
```

The argument to to_be would be the expected, not the actual:

expect $some_actual_value to_be "the expected value"

This shows in the failure messages for expectations. With the code:

```
fred="hello"
expect $fred to_be "junk"
```

the output is:

... `expected: hello | actual: junk`

Happy to send you pull request that fixes the problem, if you're happy to receive it.

**Comment by neopragma** [comment]
Fixed and added a test case.

@holmesjr - Thanks for reporting this. Sorry for the delay in fixing it, I've been pretty busy. Looks as if you've fixed your copy anyway. Cheers!
